### ISSUE TITLE
Gradle project sync failed

### ISSUE THREAD

**Issue by hardwinder** [cookpad/onesky-gradle-plugin#9]
When I open the library in my local, using Android Studio, I got this `gradle project sync failed` error:
<img width="803" alt="screen shot 2018-09-21 at 13 27 34" src="https://user-images.githubusercontent.com/1817921/45864186-5d73f700-bda3-11e8-830a-b5318368c0ba.png">

**Comment by kazu-matsu** [comment]
Revert "add jitpack" #10

**Comment by hardwinder** [comment]
back to 🍏 👍
